### ISSUE TITLE
Leaves FFXIV APP without interface after latest update

### ISSUE THREAD

**Issue by LagunaLoire** [dreams00/ffxivapp-plugin-gatherer-timer#3]
This is what I am greeted by in the app:
http://imgur.com/mgOWvVC

A fresh reintall of the app leaves it with an interface, as soon as I install the gathering plugin, restart the app, it goes to plain white. 
Please update the UI portion of your plugin, I really love using it as it makes life easier and hate having to do without it!

**Comment by dreams00** [comment]
Thank you for information.
Rebuild, commit, and push completed. (1.0.5593.15704)
